image: ubuntu:19.10

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

before_script:
  - apt update -yqq > /dev/null 2>&1
  - apt install git sudo zip unzip -yqq > /dev/null 2>&1

build_hrudelin_plugin_release:
  stage: build
  only:
    # only in build branch
    refs:
      - build
  artifacts:
    paths:
      - hrudelin-*.zip
  script:
    - ./version.sh
